_wandb:
    value:
        cli_version: 0.22.2
        e:
            09ibj3lagyusoaxz8j4c5kg8970btzzb:
                args:
                    - dqn
                    - --env-id
                    - "2"
                    - --episodes
                    - "50"
                    - --wandb
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "499963174912"
                        used: "468748922880"
                email: sinitskii.mi@phystech.edu
                executable: /opt/anaconda3/bin/python
                git:
                    commit: 81645cd52fd18446a9039593c6adbaf969e4c9c3
                    remote: https://github.com/Max8TaganskyGang/rl-gridworld.git
                host: MacBook-Pro-Maksim.local
                memory:
                    total: "17179869184"
                os: macOS-14.6.1-x86_64-i386-64bit
                program: /Users/makssinitskiy/rl_gridworld/train.py
                python: CPython 3.12.2
                root: /Users/makssinitskiy/rl_gridworld
                startedAt: "2025-10-20T08:40:43.641563Z"
                writerId: 09ibj3lagyusoaxz8j4c5kg8970btzzb
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 11
                - 49
            "2":
                - 1
                - 11
                - 49
            "3":
                - 2
                - 16
            "4": 3.12.2
            "5": 0.22.2
            "6": 4.51.3
            "12": 0.22.2
            "13": darwin-x86_64
algorithm:
    value: DQN
batch_size:
    value: 64
buffer_size:
    value: 0
env_size:
    value: 5x5
episodes:
    value: 50
epsilon_start:
    value: 1
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
max_steps:
    value: 100
n_colors:
    value: 5
obstacles:
    value: 0
